// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtuL5VchG9K6vlQ_LBmiVEjNaQ6biT6b0',
    appId: '1:1062420181883:web:fb1a4b7b8f53d479f7c3de',
    messagingSenderId: '1062420181883',
    projectId: 'login-fish',
    authDomain: 'login-fish.firebaseapp.com',
    storageBucket: 'login-fish.firebasestorage.app',
    measurementId: 'G-1HDT4B7N4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrHo2vS9bZW0lY4vsCRP3w6CG0MXE76cQ',
    appId: '1:1062420181883:android:425f0b63a3aad316f7c3de',
    messagingSenderId: '1062420181883',
    projectId: 'login-fish',
    storageBucket: 'login-fish.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_olhtm5bf8ThHugiAREjViks3oK9Srmw',
    appId: '1:1062420181883:ios:4960678e76f680e4f7c3de',
    messagingSenderId: '1062420181883',
    projectId: 'login-fish',
    storageBucket: 'login-fish.firebasestorage.app',
    iosBundleId: 'com.example.loginFishApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_olhtm5bf8ThHugiAREjViks3oK9Srmw',
    appId: '1:1062420181883:ios:4960678e76f680e4f7c3de',
    messagingSenderId: '1062420181883',
    projectId: 'login-fish',
    storageBucket: 'login-fish.firebasestorage.app',
    iosBundleId: 'com.example.loginFishApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtuL5VchG9K6vlQ_LBmiVEjNaQ6biT6b0',
    appId: '1:1062420181883:web:42c1d04f6f53a74df7c3de',
    messagingSenderId: '1062420181883',
    projectId: 'login-fish',
    authDomain: 'login-fish.firebaseapp.com',
    storageBucket: 'login-fish.firebasestorage.app',
    measurementId: 'G-N2KK000PKP',
  );

}